export const useProjects = () => {
	const projects = [
		// ==========================================
		// TIER 1: FEATURED (Home & Detail)
		// ==========================================
		{
			id: "dely-sign",
			tier: 1,
			title: "Dely Sign",
			category: "Web App",
			year: "2025 - Present",
			tags: ["Web App", "Privacy", "Tool"],
			image: "",
			desc: "A pure client-side web application for signing, editing, and manipulating PDF documents securely without any server uploads.",
			challenge:
				'The biggest hurdle was the Browser History behavior. Users expect the "Back" button to undo their last drawing/action, but standard browser behavior exits the app.',
			solution:
				'I implemented a custom "Fake State" strategy using the History API to intercept back-navigation for Undo/Redo actions.',
			keyFeatures: [
				"100% Client-Side Processing",
				"Smart History API (Undo/Redo)",
				"Auto-Transparent Signature",
				"PWA Share Target API",
				"IndexedDB Persistence",
			],
			tech: ["Vue 3", "Vite", "Konva", "pdf-lib", "IndexedDB"],
			link: "https://sign.delylabs.com",
			featured: true,
			stats: "v1.5 Public Release",
		},
		{
			id: "narajiwa",
			tier: 1,
			title: "Narajiwa",
			category: "Web App",
			year: "2024 - Present",
			tags: ["Web App", "Mental Health"],
			image: "",
			desc: "A comprehensive mental health platform connecting users with psychologists through real-time booking, chat, and assessment tools.",
			challenge:
				"Creating a seamless bridge between patients and psychologists while ensuring strict data privacy for medical records.",
			solution:
				"Designed a scalable fullstack architecture with robust RBAC. Integrated Midtrans for payments and WebSocket for chat.",
			keyFeatures: [
				"Real-time Counseling Chat",
				"Psychologist Booking System",
				"Secure Medical Record Storage",
				"Hult Prize Winner 2024",
			],
			tech: ["Laravel", "MySQL", "Bootstrap", "WebSocket"],
			link: "https://narajiwa.com",
			featured: true,
			stats: "1st Place Hult Prize",
		},

		// ==========================================
		// TIER 2: DELY SUITE
		// ==========================================
		{
			id: "dely-terbilang",
			tier: 2,
			title: "Dely Terbilang",
			category: "Web App",
			year: "2025 - Present",
			tags: ["Web App", "Privacy", "Tool"],
			desc: "An advanced number-to-text converter capable of handling extreme precision (up to 64 digits).",
			tech: ["JavaScript", "BigInt", "SheetJS"],
			link: "https://terbilang.delylabs.com",
			featured: false,
		},
		{
			id: "dely-compare",
			tier: 2,
			title: "Dely Compare",
			category: "Web App",
			year: "2025 - Present",
			tags: ["Web App", "Privacy", "Tool"],
			desc: "Text and code comparison tool utilizing Diff algorithms to highlight changes and detect plagiarism.",
			tech: ["Vue 3", "Diff Algo"],
			link: "https://compare.delylabs.com",
			featured: false,
		},
		{
			id: "dely-kit",
			tier: 2,
			title: "Dely Kit",
			category: "Web App",
			year: "2025 - Present",
			tags: ["Web App", "Privacy", "Tool"],
			desc: "A suite of text manipulation tools (Case Converter, Cleaner, Sorter) designed for quick developer tasks.",
			tech: ["Vue 3", "Regex"],
			link: "https://kit.delylabs.com",
			featured: false,
		},

		// ==========================================
		// TIER 3: MAJOR PROJECTS
		// ==========================================
		{
			id: "dely-labs",
			tier: 3,
			title: "Dely Labs Official Website",
			category: "Web App",
			year: "2025 - Present",
			tags: ["Web App", "Company Profile"],
			desc: "The parent brand website for Dely suite tools. Features a modern, high-performance landing page built with Nuxt.",
			tech: ["Nuxt", "Tailwind", "Motion"],
			link: "https://delylabs.com",
			image: "",
			featured: false,
		},
		{
			id: "roboboat",
			tier: 3,
			title: "Bengawan UV Roboboat",
			category: "Web App",
			year: "2025",
			tags: ["Web App", "Robotics"],
			desc: "Official team website with custom full-text search engine for static content and dynamic articles.",
			tech: ["Nuxt", "Tailwind", "Content API"],
			link: "https://github.com/alfikiafan/roboboat-bengawan",
			image: "",
			featured: false,
		},
		{
			id: "euy-app",
			tier: 3,
			title: "EUY: Eat Up to You",
			category: "Mobile App",
			year: "2023",
			tags: ["Mobile App", "AI & Data"],
			desc: "Bangkit Capstone. AI-powered recipe finder based on ingredients scanned/input by user.",
			tech: ["Android", "TensorFlow Lite", "Cloud"],
			link: "https://github.com/alfikiafan/euy-app",
			featured: false,
		},
		{
			id: "sentiment-analysis",
			tier: 3,
			title: "Sentiment Analysis",
			category: "AI & Data",
			year: "2024",
			tags: ["AI & Data", "NLP"],
			desc: "Advanced NLP using ResNet, Bi-LSTM, and CNN to visualize sentiment distribution from app reviews.",
			tech: ["Python", "Bi-LSTM", "NLP"],
			link: "https://github.com/alfikiafan/sentiment-analysis",
			featured: false,
		},
		{
			id: "tourism-recommender",
			tier: 3,
			title: "Tourism Recommender",
			category: "AI & Data",
			year: "2024",
			tags: ["AI & Data", "Recommender System"],
			desc: "Hybrid engine (Content-based & Collaborative Filtering) for travel destinations.",
			tech: ["Python", "TensorFlow", "RecSys"],
			link: "https://github.com/alfikiafan/tourism-recommender",
			featured: false,
		},
		{
			id: "brain-tumor",
			tier: 3,
			title: "Brain Tumor Classification",
			category: "AI & Data",
			year: "2024",
			tags: ["AI & Data", "Image Processing"],
			desc: "Medical image processing pipeline using HOG and SVM for classification.",
			tech: ["Python", "SVM", "Image Proc"],
			link: "https://github.com/alfikiafan/brain-tumor-classifier",
			featured: false,
		},
		{
			id: "heart-disease",
			tier: 3,
			title: "Heart Disease Analytics",
			category: "AI & Data",
			year: "2024",
			tags: ["AI & Data", "Data Analysis"],
			desc: "Data analysis project to identify key indicators of heart disease using statistical modeling.",
			tech: ["Python", "Pandas"],
			link: "#",
			featured: false,
		},
		{
			id: "air-quality",
			tier: 3,
			title: "Air Quality Analysis",
			category: "AI & Data",
			year: "2024",
			tags: ["AI & Data", "Data Visualization"],
			desc: "Time-series analysis of air quality data to visualize trends and pollutant levels.",
			tech: ["Python", "Matplotlib"],
			link: "#",
			featured: false,
		},

		// ==========================================
		// TIER 4: ACADEMIC & FUN
		// ==========================================
		{
			id: "documently",
			tier: 4,
			title: "Documently Website",
			category: "Web App",
			year: "2023-2025",
			tags: ["Web App", "Business"],
			desc: "A landing page for my typing service business. Simple, fast, and optimized for conversion (WhatsApp leads).",
			tech: ["HTML5", "CSS3", "JavaScript"],
			link: "https://documently.id",
			featured: false,
		},
		{
			id: "pemira-uns",
			tier: 4,
			title: "PEMIRA UNS Voting",
			category: "Web App",
			year: "2024",
			tags: ["Web App", "E-Voting"],
			desc: "High-traffic e-voting platform for Student Executive Board (BEM) election.",
			tech: ["Laravel", "MySQL", "Bootstrap"],
			link: "https://github.com/alfikiafan/pemirauns",
			featured: false,
		},
		{
			id: "myapotex",
			tier: 4,
			title: "MyApotex",
			year: "2023",
			category: "Web App",
			tags: ["Web App", "Inventory"],
			desc: "Pharmacy management system handling inventory, sales, and reporting.",
			tech: ["Laravel", "MySQL"],
			link: "https://github.com/alfikiafan/myapotex",
			featured: false,
		},
		{
			id: "sipinjam",
			tier: 4,
			title: "Sipinjam",
			category: "Web App",
			year: "2023",
			tags: ["Web App", "Inventory"],
			desc: "Inventory borrowing system for organization units.",
			tech: ["Laravel", "MySQL"],
			link: "https://github.com/alfikiafan/sipinjam",
			featured: false,
		},
		{
			id: "pandawa",
			tier: 4,
			title: "Pandawa Encyclopedia",
			category: "Mobile App",
			year: "2022",
			tags: ["Mobile App", "Educational"],
			desc: "Educational app exploring Wayang puppetry culture.",
			tech: ["Flutter", "Dart"],
			link: "https://github.com/alfikiafan/pandawa",
			featured: false,
		},
		{
			id: "country-encyclopedia",
			tier: 4,
			title: "Country Encyclopedia",
			category: "Web App",
			year: "2023",
			tags: ["Web App", "Educational"],
			desc: "Dynamic web encyclopedia fetching real-time country data.",
			tech: ["Node.js", "Express"],
			link: "https://github.com/alfikiafan/country-encyclopedia",
			featured: false,
		},
		{
			id: "pikachu-jump",
			tier: 4,
			title: "Pikachu Jump",
			category: "Game",
			year: "2022",
			tags: ["Game"],
			desc: "C++ game modification based on Doodle Jump with custom sprites.",
			tech: ["C++", "SFML"],
			link: "https://github.com/alfikiafan/pikachu-jump",
			featured: false,
		},
		{
			id: "kuis-kata-baku",
			tier: 4,
			title: "Kuis Kata Baku",
			category: "Game",
			year: "2023",
			tags: ["Game", "Web App", "Educational"],
			desc: "Educational game with 1000+ word pool, timer, and audio.",
			tech: ["JS DOM", "HTML5"],
			link: "https://github.com/alfikiafan/kuis-kata-baku",
			featured: false,
		},
		{
			id: "turing-machine",
			tier: 4,
			title: "Turing Machine Simulator",
			category: "Web App",
			year: "2023",
			tags: ["Web App", "Educational"],
			desc: "Simulation of Turing Machines to demonstrate computational theories.",
			tech: ["JS", "HTML5"],
			link: "https://github.com/alfikiafan/turing-machine-simulator",
			featured: false,
		},
		{
			id: "plagiarism-checker",
			tier: 4,
			title: "Plagiarism Checker",
			category: "Desktop App",
			year: "2024",
			tags: ["Desktop App", "AI & Data", "NLP"],
			desc: "Desktop app to detect text similarity using string matching.",
			tech: ["Python", "Tkinter"],
			link: "https://github.com/alfikiafan/plagiarism-checker",
			featured: false,
		},
		{
			id: "bookshelf-app",
			tier: 4,
			title: "Bookshelf App",
			category: "Web App",
			year: "2023",
			tags: ["Web App", "Educational"],
			desc: "Responsive virtual bookshelf management with read status tracking.",
			tech: ["JavaScript", "DOM"],
			link: "https://github.com/alfikiafan/bookshelf-app",
			featured: false,
		},
	];

	return { projects };
};
